name: gogpt
on:
  push:
    branches:
    - main
    - dev
  pull_request:
    branches:
    - main

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'

      - name: Install devcontainer-cli
        run: npm install -g @devcontainers/cli

      - name: Checkout code
        uses: actions/checkout@v3

      # build and start devcontainer. Capture the container ID and exec make lint and make test
      - name: Run tests
        run: |
          ls -la
          devcontainer up --workspace-folder .
          devcontainer exec --workspace-folder . bash -c "make lint"
          devcontainer exec --workspace-folder . bash -c "make test"

  release:
    needs: tests
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/dev'
    permissions:
      contents: write
      packages: write
      pull-requests: write
      issues: write
    steps:
      - uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18
      - name: create semantic release
        env:
          GITHUB_TOKEN: ${{ secrets.SEMANTIC_RELEASE }}
          GIT_AUTHOR_NAME: semantic-bot
          GIT_AUTHOR_EMAIL: semantic-bot@noemail.com
        run: |
          npm install @semantic-release/exec
          npm install @semantic-release/github
          npm install @semantic-release/git @semantic-release/changelog -D
          npx semantic-release
