name: gogpt
on:
  push:
    branches:
    - main
    - dev
    - feat/*
  pull_request:
    branches:
    - main
    - dev

jobs:
  Tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18

      - name: lint
        run: |
          make lint

      - name: test
        run: |
          make test-ci

  release:
    needs: Tests
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/dev'
    steps:
      - uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18
      - name: create semantic release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GIT_AUTHOR_NAME: semantic-bot
          GIT_AUTHOR_EMAIL: semantic-bot@noeamil.com
        run: |
          npm install @semantic-release/exec
          npm install @semantic-release/github
          npm install @semantic-release/git @semantic-release/changelog -D
          npx semantic-release
